### ISSUE TITLE
API pagination does not work

### ISSUE THREAD

**Issue by hellpirat** [amureki/covidapp#2]
Summary always returns the same data

```
GET:  https://covidapp.herokuapp.com/api/v0/summary/?page=6
```

**Comment by amureki** [comment]
@hellpirat wow, thank you for noticing! I'll take care of it as soon as I can.

**Comment by amureki** [comment]
@hellpirat actually this endpoint is meant (at least for now) to return all summary reports objects, paginated. If you check results - the data is different, format is the same.

You might be interested in https://covidapp.herokuapp.com/api/v0/summary/latest which gives you the latest report.

I am still in the process of designing this API, so it is not ideal yet. Suggestions are more than welcome! :)

Best,
Rust

**Comment by amureki** [comment]
@hellpirat small update, I am testing new API structure here:
https://covidapp.herokuapp.com/swagger/ (under `dev` tag)

Could you, please, take a look and tell me what do you think about it?

**Comment by hellpirat** [comment]
@amureki Looks good, but now I don't have any idea how to use it and what to do with that. 🤔 Maybe add a page for each country with detail information and history data 🤔 

Also, I have been thinking it would be a good idea to add a search by country.  q=text

**Comment by amureki** [comment]
@hellpirat I think it is up to you to find out how to use it :)
Yeah, per-country page would be nice, you can use my new `https://covidapp.herokuapp.com/api/dev/region/germany/` endpoint.
Or stats per-day: `https://covidapp.herokuapp.com/api/dev/region/germany/2020-03-09/`

Regarding the search: the problem I currently have - weird region names I am getting from `Johns Hopkins CSSE `. I am thinking about trying to map this to iso 3166, but this requires some more work.
Currently I am putting slugs and region names (mapping, basically) I am getting from this data source in this endpoint: https://covidapp.herokuapp.com/api/dev/regions/

And yeah, this `dev` version is meant to break. I think, I will release current `dev` API as `v1` soon, if I am happy enough with the design. :)

**Comment by amureki** [comment]
I will close this ticket, due to the fact that I merged https://github.com/amureki/covidapp/pull/4 
It introduces API `v1`, which feels cleaner and more usable for me.

Feel free to add more suggestions and comments or reopen this issue! ❤️ 

Best,
Rust
