### ISSUE TITLE
Can you add CORS headers ?

### ISSUE THREAD

**Issue by hellpirat** [amureki/covidapp#3]
Based on your repo I build a front-end with svelte(just for learning purpose) and now I using https://cors-anywhere.herokuapp.com/ for making requests :) 

https://covid-19-tracker-4003qxa22.now.sh/ 
https://github.com/hellpirat/covid-19-tracker

**Comment by amureki** [comment]
@hellpirat I did add `django-cors-headers` and allowed access to `/api/`. Could, you, please, check it out?
